### ISSUE TITLE
fix m4 build with newer host glibc

### ISSUE THREAD

**Issue by leiflindholm** [ARM-software/arm-enterprise-acs#72]
Trying to build enterprise-acs on current Debian Buster fails with:
```
| make[3]: Entering directory '/work/git/ARM/arm-enterprise-acs/luv/build/tmp/work/x86_64-linux/m4-native/1.4.18-r0/build/lib'
| gcc   -I. -I../../m4-1.4.18/lib   -isystem/work/git/ARM/arm-enterprise-acs/luv/build/tmp/work/x86_64-linux/m4-native/1.4.18-r0/recipe-sysroot-native/usr/include  -isystem/work/git/ARM/arm-enterprise-acs/luv/build/tmp/work/x86_64-linux/m4-native/1.4.18-r0/recipe-sysroot-native/usr/include -O2 -pipe -c -o freadahead.o ../../m4-1.4.18/lib/freadahead.c
| gcc   -I. -I../../m4-1.4.18/lib   -isystem/work/git/ARM/arm-enterprise-acs/luv/build/tmp/work/x86_64-linux/m4-native/1.4.18-r0/recipe-sysroot-native/usr/include  -isystem/work/git/ARM/arm-enterprise-acs/luv/build/tmp/work/x86_64-linux/m4-native/1.4.18-r0/recipe-sysroot-native/usr/include -O2 -pipe -c -o fseeko.o ../../m4-1.4.18/lib/fseeko.c
| ../../m4-1.4.18/lib/fseeko.c: In function ‘rpl_fseeko’:
| ../../m4-1.4.18/lib/fseeko.c:110:4: error: #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
|    #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
|     ^~~~~
| ../../m4-1.4.18/lib/freadahead.c: In function ‘freadahead’:
| ../../m4-1.4.18/lib/freadahead.c:92:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
|   #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
|    ^~~~~
| make[3]: *** [Makefile:1915: fseeko.o] Error 1
```

A patch exists upstream in:

http://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/meta/recipes-devtools/m4?h=thud&id=95ca077ab871ceff46c2052f324f879a1d624ff4

**Comment by edhay** [comment]
Solution verification is in progress.
The fix will be incorporated in the upcoming Enterprise ACS v3.0

**Comment by edhay** [comment]
Hi Leif, 

   In the Enterprise ACS v3.0 release, we have incorporated the patch mentioned in this issue (#72 )and also the bison patch referred to in the issue #73 . 
In addition, we have incorporated more patches to achieve a successful build in Ubuntu 20.04.
Requesting your team to please try the same from latest code.

Please feel free to contact us for any clarifications or any issues faced.

-- Enterprise ACS Support

**Comment by bcran** [comment]
I've tested this on Ubuntu 20.04 and the build succeeds.

**Comment by edhay** [comment]
Closing this issue as per confirmation from @bcran.

**Comment by Samson992** [comment]
> I've tested this on Ubuntu 20.04 and the build succeeds.

How you recover from that error

**Comment by bcran** [comment]
Bison 2.6.2 was released in 2012. Can you use a newer version?

**Comment by Samson992** [comment]
For Swak4foam support only on bison 2.4 to 2.6 series
